[package]
name = "dcs-miz-repacker"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = { version = "3", features = ["derive"] }
crossterm = "0.23"
serde_derive = "1"
once_cell = "1"
walkdir = "2"
zip = "0.6"
serde = "1"
anyhow = "1"
regex = "1"
toml = "0.5"
rand = "0.8"
