on:
  - push

name: Continuous Integration

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: actions/upload-artifact@v3
        with:
          name: dcs-miz-repacker
          path: target/release/dcs-miz-repacker.exe
  release:
    name: Release
    needs: ["build"]
    runs-on: windows-latest
    if: startsWith(github.event.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dcs-miz-repacker
      - uses: ncipollo/release-action@v1
        with:
          artifacts: dcs-miz-repacker.exe
          token: ${{ secrets.GITHUB_TOKEN }}
